### ISSUE TITLE
로그인 시 맞는 user가 없을 경우 오류 표시

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#108]
## ☑️ 진행할 작업
- 로그인 시 맞는 user를 확인하고 없을 경우 오류를 표시한다.

## 📝 TODO
- [ ] 로그인 시 맞는 user가 있다면 바로 이슈 리스트 페이지로 넘어간다.
- [ ] 로그인 시 맞는 user가 없다면 아이디와 비밀번호가 포커스된다.
  - [ ] 포커스되면서 box 테두리가 빨간색으로 바뀐다. 

## ⚙️ 기타
- 기획서를 참고하였습니다.
