### ISSUE TITLE
색상 추가

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#12]
## **☑️ 진행할 작업**
- 프로젝트에서 사용하는 색상을 추가합니다

## **📝TODO**
- [x]  색상 변수 설정
    - [x]  Light Mode Color Palette
    - [x]  Dark Mode Color Palette

## **⚙️기타**
- 피그마 참고
