### ISSUE TITLE
IssueTracker 추가기능 구현

### ISSUE THREAD

**Issue by bread1022** [codesquad-2023-group04/issue-tracker#127]
## ☑️ 진행할 작업
- 추가로 필요한 기능을 구현합니다.

## 📝 TODO
- [x] POST (new Issue, issue detail)
- [x] 이슈상세페이지에서 해당하는 데이터의 정보를 가져오는 기능
- [x] 레이블 생성하는 기능
