### ISSUE TITLE
API연동을 위한 Network Interface구성

### ISSUE THREAD

**Issue by noah0316** [codesquad-2023-group04/issue-tracker#134]
## ☑️ 진행할 작업

- REST API 연동을 위한 Network Interface를 구성합니다.

## 📝 TODO

- [x] Network 작업을 추상화한 프로토콜 생성
- [x] HTTP status code에 따른 Error 케이스 생성
- [x] Network 작업 오류 처리
## ⚙️ 기타

- API 문서 참고
