### ISSUE TITLE
팝업창 데이터 전송

### ISSUE THREAD

**Issue by leegyeongwhan** [codesquad-2023-group04/issue-tracker#14]
## ☑️ 진행할 작업

- 담당자, 레이블, 마일스톤, 작성자를 클릭 시 관련 데이터를 응답한다. 
## 📝 TODO

- [ ]  담당자 클릭 시 담당자 리스트를 응답한다.
- [ ]  레이블 클릭 시 레이블 리스트를 응답한다.
- [ ]  마일스톤 클릭 시 마일스톤 리스트를 응답한다.
- [ ]  작성자 클릭 시 작성자 리스트를 응답한다.
