### ISSUE TITLE
이슈목록조회 헤더 구현

### ISSUE THREAD

**Issue by bread1022** [codesquad-2023-group04/issue-tracker#20]
## ☑️ 진행할 작업
- [x] 이슈목록화면 헤더영역을 표시한다

## 📝 TODO
- [x] 프로필 컴포넌트를 생성한다
- [x]  Issue Tracker 로고와 사용자프로필을 표시한다

## ⚙️ 기타

<br>
