### ISSUE TITLE
이슈 목록 드롭 다운 탭 클릭시 필터 조건 표시

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#22]
## ☑️ 진행할 작업

- 이슈 목록 드롭 다운 탭을 클릭 하면 세부적인 필터 조건이 표시 됩니다.
- 이수 목록 드롭 다운 탭은 담당자, 레이블, 마일스톤, 작성자 순으로 구성되어 있습니다.

## 📝TODO

- [ ]  드롭다운탭을 선택하면 각각의 필터설정팝업이 나타난다.
- [ ]  필터를 선택하면 조건을 필터링한 목록을 반영하고 팝업이 닫힌다.
- [ ]  필터가 적용되면 현재 검색 필터 및 정렬 지우기 버튼이 나타난다.
- [ ]  지우기 버튼을 클릭하면 필터를 초기화하고 기본상태로 돌아간다.
- [ ]  필터 후 일치값이 없으면 “검색과 일치하는 결과가 없습니다”를 표시한다.
- [ ]  드롭다운필터 설정팝업의 다른 부분을 클릭하면 팝업이 닫힌다.
- [ ]  좌측 상단 필터바 텍스트폼에 있는 텍스트를 모두 지우면 Search all issues를 표시하고 엔터시 모든 이슈 목록을 표시한다

## ⚙️기타

- 기획서를 참조하였습니다.
