### ISSUE TITLE
이슈 목록 Swipe Gesture 구현

### ISSUE THREAD

**Issue by ghost** [codesquad-2023-group04/issue-tracker#25]
## ☑️ 진행할 작업

- 각 list item에 맞는 swipe gesture 화면을 구성합니다
- 적용해야할 list item의 종류는 3가지(Issue, label, milestone)
- gesture 화면의 종류는 2가지(편집/삭제, 닫기/삭제)
## 📝 TODO

- [ ] Issue list item swipe gesture 화면(닫기/삭제)
- [ ] label list item swipe gesture 화면(편집/삭제)
- [ ] milestone list item swipe gesture 화면(편집/삭제)
