### ISSUE TITLE
이슈 팝업창 데이터 전송

### ISSUE THREAD

**Issue by leegyeongwhan** [codesquad-2023-group04/issue-tracker#29]
## **☑️ 진행할 작업**

- 이슈 팝업창에서 필요한 담당자, 레이블, 마일스톤, 작성자 팝업 데이터 전송

## **📝TODO**

- [ ]  담당자 데이터 전송
- [ ]  레이블 데이터 전송
- [ ]  작성자 데이터 전송

## **⚙️기타**
