### ISSUE TITLE
text area 컴포넌트 생성

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#39]
## ☑️ 진행할 작업

- text Area 컴포넌트를 생성한다.

## 📝TODO

- [ ]  제목을 작성할 수 있는 컴포넌트를 생성한다.
- [ ]  본문을 작성할 수 있는 컴포넌트를 생성한다.
- [ ]  파일 첨부는 버튼 컴포넌트를 이용하여 생성한다.

## ⚙️기타

- 기획서를 참고하였습니다.
