### ISSUE TITLE
SwiftLint 적용

### ISSUE THREAD

**Issue by noah0316** [codesquad-2023-group04/issue-tracker#4]
## ☑️ 진행할 작업

- 일관된 코드를 작성하기 위해 회의를 통해 정한 SwiftLint를 도입합니다.
## 📝 TODO

- [x] SwiftLint 패키지 설치
- [x] SwiftLint Rule 추가
- [x] Build Phase 설정
## ⚙️ 기타

- SwiftLint rule Wiki에 업로드 예정
