### ISSUE TITLE
text input 컴포넌트 생성

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#45]
## ☑️ 진행할 작업
- text input 컴포넌트를 생성하고 컴포넌트를 이용하여 기존의 필터바를 수정합니다.

## 📝 TODO
- [x] text input 컴포넌트를 생성합니다.
- [x] 아이콘의 위치가 오른쪽에 배치되는 스타일 컴포넌트를 생성합니다.
- [x] 아이콘의 위치가 위쪽에 배치되는 스타일 컴포넌트를 생성합니다.

## ⚙️ 기타
- 기존의 필터바에서 input 부분을 따로 컴포넌트로 제작하여 다른 곳에서 재사용할 수 있게 제작하였습니다.
