### ISSUE TITLE
리스트 아이템 커스텀 셀 레이아웃 구성

### ISSUE THREAD

**Issue by noah0316** [codesquad-2023-group04/issue-tracker#6]
## ☑️ 진행할 작업

- 리스트로 보여지는 항목들에 대한 커스텀 셀 레이아웃을 구성합니다.
## 📝 TODO

- [x] 이슈 리스트 아이템
- [x] 레이블 리스트 아이템
- [ ] 마일스톤 리스트 아이템
- [ ] 이슈 디테일 헤더 아이템
- [ ] 댓글 리스트 아이템

## ⚙️ 기타

- 피그마 참고
