### ISSUE TITLE
버튼 컴포넌트 스타일 변경

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#65]
## ☑️ 진행할 작업
- 기존 버튼 컴포넌트 스타일을 변경 합니다.

## 📝 TODO
- [ ] 버튼 컴포넌트 내부 필요한 스타일을 정리한다.
- [ ] 필요한 스타일을 정리해서 버튼 컴포넌트 스타일을 변경한다.
- [ ] 상단에 버튼을 사용한 컴포넌트를 변경한다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
