### ISSUE TITLE
필터바 필터 적용

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#66]
## ☑️ 진행할 작업
- 필터바 부분에서 모달 창을 클릭하면 필터바를 적용한다.

## 📝 TODO
- [ ] 필터 부분 필터 적용
  -  [ ] 내가 작성한 이슈 클릭 시 이슈 리스트에 표시 된다.
  -  [ ] 나에게 할당된 이슈 클릭 시 이슈 리스트에 표시 된다.
  -  [ ] 내가 댓글을 남긴 이슈 클릭시 이슈 리스트에 표시 된다.
  - [ ] 열린 이슈 클릭 시 이슈 리스트에 표시 된다.
  - [ ] 닫힌 이슈 클릭 시 이슈 리스트에 표시 된다.
- [ ] 필터 검색창 필터 적용
  -  [ ] 내가 작성한 이슈 검색 시 이슈 리스트에 표시 된다.
  -  [ ] 나에게 할당된 이슈 검색 시 이슈 리스트에 표시 된다.
  -  [ ] 내가 댓글을 남긴 이슈 검색 시 이슈 리스트에 표시 된다.
  - [ ] 열린 이슈 검색 시 이슈 리스트에 표시 된다.
 
## ⚙️ 기타
- 기획서를 참고하였습니다.
