### ISSUE TITLE
text input 컴포넌트 상태 적용

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#76]
## ☑️ 진행할 작업
- 기존의 text input 컴포넌트 상태를 적용합니다.

## 📝 TODO
- [ ] 라벨이 없는 plcaeholder 상태의 컴포넌트를 제작한다.
- [ ] 왼쪽에 라벨이 고정되어 있는 상태에서 placeholder 상태의 컴포넌트를 제작한다.
- [ ] 위쪽에 라벨이 고정되어 있는 상태에서 placeholder상태의 컴포넌트를 제작한다.
- [ ] 클릭 시 배경화면이 흰색이 변한고, place holder 사라진다.
- [ ] 완료 버튼을 클릭하면 입력이 안된부분은 에러가 뜬다.
- [ ] 입력하는 순간 완료버튼의 disabled이 풀린다. 
## ⚙️ 기타
- 기획서를 참고하였습니다.
