### ISSUE TITLE
text area 컴포넌트 상태 적용

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#77]
## ☑️ 진행할 작업
- 파일첨부하기 기능을 만들고, 상태를 적용한다.

## 📝 TODO
- [ ] 파일 첨부하기 기능을 만든다.
- [ ] active일 때, 상태를 만든다.
- [ ] typing일 때, 상태를 만든다.
- [ ] typing+counter일 때, 상태를 만든다.
- [ ] typede 상태를 만든다
- [ ] Disabled 상태를 만든다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
