### ISSUE TITLE
사이드 바 드롭다운 탭 적용

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#79]
## ☑️ 진행할 작업
- 사이드 바 클릭 시, 드롭다운 탭을 적용합니다.

## 📝 TODO
- [x] 담당자 드롭다운 탭을 적용합니다.
- [x] 레이블 드롭다운 탭을 적용합니다.
- [x] 마일스톤 드롭다운 탭을 적용합니다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
