### ISSUE TITLE
information Tag 컴포넌트 생성

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#94]
## ☑️ 진행할 작업
- 열린 이슈인지, 오픈 이슈인지 확인하는 tag 컴포넌트를 만듭니다.

## 📝 TODO
- [ ] 열린 이슈 태그를 만듭니다.
- [ ] 오픈 이슈 태그를 만듭니다.
- [ ] 빈 이슈 태그를 만듭니다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
