### ISSUE TITLE
comment Elements 컴포넌트 생성

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#95]
## ☑️ 진행할 작업
- 코멘트 부분 컴포넌트를 생성합니다.

## 📝 TODO
- [ ] defatult 상태를 생성합니다.
- [ ] edit 상태를 생성합니다.
- [ ] Action History 상태를 생성합니다.
- [ ] 
## ⚙️ 기타
- 기획서를 참고하였습니다.
