### ISSUE TITLE
issueDetail 사이드바 구현

### ISSUE THREAD

**Issue by yesolyo** [codesquad-2023-group04/issue-tracker#98]
## ☑️ 진행할 작업
- issueDetail 사이드 바를 구현합니다.
## 📝 TODO
- [ ] 작성 시 선택했던 담당자, 레이블, 마일스톤을 선택합니다.
- [ ] 사이드 바 클릭 시 변경 할 수 있습니다.
- [ ] 이슈 삭제 시 모든 이슈가 삭제됩니다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
